<a href="https://colab.research.google.com/github/Adah-K/ML/blob/main/ML_Individual_Task1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#IMPORTING LIBRARIES

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

#INITIALIZING VALUES FOR SLOPE AND Y-INTERCEPT

In [2]:
m = 0.5
c = 0.2

#GENERATING VALUES OF X AND Y

In [3]:
X = np.random.uniform(10,90,100) # 10 min, 90 max, 100 values

In [4]:
X

array([15.05794548, 85.78041139, 70.52888917, 47.67091649, 36.54829607,
       21.49614136, 31.83001901, 77.27907022, 50.91314383, 69.50328176,
       64.52717188, 70.83291303, 31.23593245, 45.90516464, 25.5789528 ,
       19.70952243, 80.59105445, 13.95706248, 52.7964006 , 36.61307888,
       29.91006926, 11.11013545, 15.20900806, 71.90107159, 66.52005785,
       41.96662138, 84.83698941, 34.57264622, 26.52854685, 20.31110498,
       49.88139201, 46.38956434, 33.35078808, 55.80356248, 61.59422164,
       43.73728211, 38.62272544, 70.12764921, 45.33284772, 68.1141537 ,
       73.47608796, 81.25375802, 63.01584122, 54.00445338, 86.45318728,
       15.66121549, 75.60572529, 82.10144541, 82.39726307, 53.4834531 ,
       36.34102188, 65.15205618, 46.95491376, 52.68729044, 28.89748186,
       23.72500926, 59.61513043, 85.50252418, 78.39418822, 56.73262592,
       17.60908524, 64.012927  , 28.94586327, 27.71113918, 17.40479393,
       56.13721939, 42.46282124, 12.49368566, 84.16703883, 88.05

In [5]:
y = m*X+c

In [6]:
y

array([ 7.72897274, 43.09020569, 35.46444458, 24.03545825, 18.47414804,
       10.94807068, 16.1150095 , 38.83953511, 25.65657192, 34.95164088,
       32.46358594, 35.61645651, 15.81796623, 23.15258232, 12.9894764 ,
       10.05476121, 40.49552722,  7.17853124, 26.5982003 , 18.50653944,
       15.15503463,  5.75506772,  7.80450403, 36.1505358 , 33.46002893,
       21.18331069, 42.61849471, 17.48632311, 13.46427342, 10.35555249,
       25.14069601, 23.39478217, 16.87539404, 28.10178124, 30.99711082,
       22.06864106, 19.51136272, 35.26382461, 22.86642386, 34.25707685,
       36.93804398, 40.82687901, 31.70792061, 27.20222669, 43.42659364,
        8.03060774, 38.00286264, 41.2507227 , 41.39863153, 26.94172655,
       18.37051094, 32.77602809, 23.67745688, 26.54364522, 14.64874093,
       12.06250463, 30.00756521, 42.95126209, 39.39709411, 28.56631296,
        9.00454262, 32.2064635 , 14.67293164, 14.05556959,  8.90239696,
       28.2686097 , 21.43141062,  6.44684283, 42.28351942, 44.22

In [7]:
noise = np.random.normal(1,15,100)
noise

array([ 2.87893143e+01, -2.45040399e+01, -5.22980671e+01,  3.33160096e+00,
       -1.15163452e+01,  1.85514803e+01, -1.27060823e+00,  1.34749467e+01,
       -3.77948251e+00, -1.12044240e+01,  7.52249237e+00, -8.47952552e+00,
       -1.95652827e+01, -4.62174003e+00,  6.93596101e+00,  1.85391854e+01,
        4.65640435e-01,  3.16745658e+01,  4.47551408e+00, -1.10455176e+01,
        2.79165992e+00,  2.37209500e+00, -1.68315278e+01, -1.59305219e+01,
       -1.40631161e+01,  3.53805207e+00, -1.79289213e+01,  4.53043219e+00,
       -2.45848631e+01, -3.61640992e+01, -1.95848528e+01, -7.48727110e+00,
        1.44438699e+01, -6.23919287e+00,  1.64504866e+00,  5.41487332e+00,
       -2.13599512e+00,  3.60756846e+00,  3.45355011e+00, -1.24614647e+01,
       -3.74985138e+01, -3.40250753e+00,  1.22647458e+00,  2.79401414e+01,
       -3.54181509e+01, -1.04989085e+00, -1.26278634e+01,  1.73942774e+01,
        2.44136029e+00,  8.96451195e+00, -2.87204370e+00, -3.66021091e-01,
       -7.90004420e+00,  

In [8]:
Y = y+noise
Y

array([ 36.51828708,  18.58616578, -16.83362256,  27.36705921,
         6.9578028 ,  29.49955099,  14.84440128,  52.31448179,
        21.8770894 ,  23.7472169 ,  39.98607831,  27.13693099,
        -3.7473165 ,  18.53084228,  19.92543741,  28.59394661,
        40.96116766,  38.85309702,  31.07371438,   7.46102182,
        17.94669455,   8.12716272,  -9.02702372,  20.22001387,
        19.39691279,  24.72136276,  24.68957338,  22.0167553 ,
       -11.12058967, -25.80854673,   5.55584318,  15.90751107,
        31.31926391,  21.86258837,  32.64215948,  27.48351438,
        17.3753676 ,  38.87139307,  26.31997397,  21.79561212,
        -0.56046982,  37.42437148,  32.93439519,  55.14236813,
         8.00844276,   6.9807169 ,  25.37499924,  58.64500012,
        43.83999182,  35.9062385 ,  15.49846724,  32.410007  ,
        15.77741268,  51.89310996,  37.61001886,  11.90857298,
        31.26947411,  65.83959003,  28.04913906,  13.56071633,
        -5.37211939,  34.30121705,   6.75001637,  34.65

# MSE FUNCTION AS PERFORMANCE MEASURE

In [10]:
def mse(N,Y,Y_hat):
  return(1/N)*sum(Y-Y_hat)**2

#GRADIENT DESCENT AS LEARNING ALGORITHM

In [ ]:
L = 0.001
iterations = 30
def gradient_descent_lobf(m,c,N,L):
  iteration_error_list =[]
  iteration_error_count =[]

  for i in range (iterations):
    Y-hat = m*X+c